"""
cli.py — RootScout command-line interface.

Usage:
    rootscout analyze --telemetry traces.pb --incident-time 2024-06-01T10:00:00Z --failing-service cart
    rootscout index --codebases /path/to/repo --output index.json
    rootscout serve --port 8000
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time as _time
from datetime import datetime, timedelta, timezone


BANNER = r"""
  ____             _   ____                  _
 |  _ \ ___   ___ | |_/ ___|  ___ ___  _   _| |_
 | |_) / _ \ / _ \| __\___ \ / __/ _ \| | | | __|
 |  _ < (_) | (_) | |_ ___) | (_| (_) | |_| | |_
 |_| \_\___/ \___/ \__|____/ \___\___/ \__,_|\__|

  Autonomous SRE Root-Cause Analysis  v0.2.0
"""


def _parse_incident_time(s: str) -> datetime:
    s = s.replace("Z", "+00:00")
    dt = datetime.fromisoformat(s)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _header(title: str, step: str = "") -> None:
    print(f"\n{'='*64}")
    if step:
        print(f"  {step}: {title}")
    else:
        print(f"  {title}")
    print(f"{'='*64}")


def _bullet(msg: str, indent: int = 2) -> None:
    print(f"{' '*indent}> {msg}")


def _sub(msg: str, indent: int = 4) -> None:
    print(f"{' '*indent}{msg}")


# ---------------------------------------------------------------------------
# Slack posting
# ---------------------------------------------------------------------------

def _post_to_slack(report: dict, context_packet: dict, args: argparse.Namespace) -> None:
    """Post the RCA report to Slack using Block Kit formatting."""
    try:
        import httpx
    except ImportError:
        print("  [WARN] httpx not installed, skipping Slack post")
        return

    token = os.getenv("SLACK_BOT_TOKEN", "").strip()
    channel = args.slack_channel or os.getenv("SLACK_ALERT_CHANNEL", "").strip()

    if not token:
        print("  [WARN] SLACK_BOT_TOKEN not set, skipping Slack post")
        return
    if not channel:
        print("  [WARN] No Slack channel specified, skipping Slack post")
        return

    root_svc = report.get("root_cause_service", "unknown")
    confidence = report.get("confidence", "?")
    reasoning = report.get("reasoning", "No reasoning provided")
    action = report.get("recommended_action", "No action suggested")
    fault_time = report.get("root_cause_datetime", "?")
    focus = context_packet.get("focus_service", args.failing_service)

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"RootScout RCA Report", "emoji": True},
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Alerting Service:*\n{focus}"},
                {"type": "mrkdwn", "text": f"*Root Cause:*\n`{root_svc}`"},
                {"type": "mrkdwn", "text": f"*Confidence:*\n{confidence}"},
                {"type": "mrkdwn", "text": f"*Fault Start:*\n{fault_time}"},
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Reasoning:*\n{reasoning[:2900]}"},
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Recommended Action:*\n```{action}```"},
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated by RootScout v0.2.0 | Provider: {args.provider}"},
            ],
        },
    ]

    print(f"\n  Posting to Slack channel: {channel}")
    try:
        resp = httpx.post(
            "https://slack.com/api/chat.postMessage",
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
            json={"channel": channel, "text": f"RCA Report: {root_svc}", "blocks": blocks},
            timeout=15,
        )
        data = resp.json()
        if data.get("ok"):
            print(f"  Posted to Slack successfully (ts={data.get('ts')})")
        else:
            print(f"  [WARN] Slack API error: {data.get('error')}")
    except Exception as e:
        print(f"  [WARN] Slack post failed: {e}")


# ---------------------------------------------------------------------------
# analyze — the main RCA pipeline
# ---------------------------------------------------------------------------

def cmd_analyze(args: argparse.Namespace) -> None:
    """Run the full RootScout analysis pipeline."""
    from dotenv import load_dotenv
    load_dotenv()

    from rootscout.graph.graph_builder import GraphBuilder
    from rootscout.graph.context_retriever import ContextRetriever
    from rootscout.graph.agent import RCAAgent
    from rootscout.graph_sink import GraphBuilderSink
    from rootscout.llm.client import get_client

    print(BANNER)

    incident_time = _parse_incident_time(args.incident_time)
    window_hours = args.window_hours
    window_start = incident_time - timedelta(hours=window_hours)

    print(f"  Incident time:    {incident_time.isoformat()}")
    print(f"  Failing service:  {args.failing_service}")
    print(f"  Lookback window:  {window_hours}h ({window_start.isoformat()})")
    print(f"  LLM provider:     {args.provider}" + (f" / {args.model}" if args.model else ""))
    print(f"  Telemetry files:  {len(args.telemetry)}")
    if args.codebases:
        print(f"  Codebases:        {len(args.codebases)}")
    if args.slack_channel or os.getenv("SLACK_ALERT_CHANNEL"):
        ch = args.slack_channel or os.getenv("SLACK_ALERT_CHANNEL")
        print(f"  Slack channel:    {ch}")

    t0 = _time.time()

    # =====================================================================
    # Step 1: Code indexing
    # =====================================================================
    code_index = None
    if args.codebases:
        _header("Indexing codebases", "STEP 1/4")
        from rootscout.code_indexer import CodeIndexer
        indexer = CodeIndexer(args.codebases)
        code_index = indexer.build_index()

        # Show index summary
        langs = {}
        for entry in code_index.files.values():
            langs[entry.language] = langs.get(entry.language, 0) + 1
        _bullet(f"Indexed {len(code_index.files)} source files")
        for lang, count in sorted(langs.items(), key=lambda x: -x[1]):
            _sub(f"{lang}: {count} files")
        if code_index.service_map:
            _bullet(f"Detected {len(code_index.service_map)} service(s):")
            for svc, paths in code_index.service_map.items():
                _sub(f"{svc} ({len(paths)} files)")
        # Show sample of indexed symbols
        total_funcs = sum(len(e.functions) for e in code_index.files.values())
        total_classes = sum(len(e.classes) for e in code_index.files.values())
        _bullet(f"Symbols: {total_funcs} functions, {total_classes} classes")
    else:
        _header("Code indexing (skipped — no --codebases)", "STEP 1/4")

    # =====================================================================
    # Step 2: Ingest OTel telemetry
    # =====================================================================
    _header("Ingesting telemetry", "STEP 2/4")

    graph_builder = GraphBuilder()
    graph_sink = GraphBuilderSink(graph_builder)

    from rootscout.file_ingester import FileIngester, TimeWindowSink
    filtered_sink = TimeWindowSink(graph_sink, start=window_start, end=incident_time)
    file_ingester = FileIngester(sink=filtered_sink)

    total_records = 0
    for tpath in args.telemetry:
        try:
            if os.path.isdir(tpath):
                results = file_ingester.ingest_directory(tpath)
                for r in results:
                    if "error" in r:
                        _bullet(f"WARN: {os.path.basename(r['file'])}: {r['error']}")
                    else:
                        _bullet(f"{r['signal']:8s} {r['count']:4d} records from {os.path.basename(r['file'])}")
                        total_records += r["count"]
            else:
                r = file_ingester.ingest_file(tpath)
                _bullet(f"{r['signal']:8s} {r['count']:4d} records from {os.path.basename(r['file'])}")
                total_records += r["count"]
        except Exception as e:
            _bullet(f"ERROR: {tpath}: {e}")

    _bullet(f"Time window: [{window_start.strftime('%Y-%m-%d %H:%M')} .. {incident_time.strftime('%Y-%m-%d %H:%M')}]")
    _bullet(f"Records ingested: {filtered_sink.accepted} accepted, {filtered_sink.rejected} filtered out")

    # Show graph topology
    nodes = list(graph_builder.graph.nodes(data=True))
    edges = list(graph_builder.graph.edges(data=True))
    _bullet(f"Service graph: {len(nodes)} nodes, {len(edges)} edges")

    if nodes:
        _sub("")
        _sub("Discovered topology:")
        for n, data in nodes:
            status = data.get("status", "unknown").upper()
            events = data.get("recent_events", [])
            version = data.get("version", "")
            status_icon = "!!" if status == "ERROR" else "OK"
            line = f"  [{status_icon}] {n}"
            if version:
                line += f" (v{version})"
            line += f" — {len(events)} events"
            _sub(line)

        _sub("")
        _sub("Dependencies:")
        for src, dst, data in edges:
            lat = data.get("latency", "?")
            _sub(f"  {src} --> {dst}  (latency: {lat}ms)")
    else:
        _bullet("WARNING: No services found in telemetry.")
        _sub("Check that files are valid OTLP and timestamps are within window.")

    # =====================================================================
    # Step 3: Build context
    # =====================================================================
    _header(f"Building RCA context for '{args.failing_service}'", "STEP 3/4")

    retriever = ContextRetriever(graph_builder)
    context_packet = retriever.get_context(args.failing_service)

    related = context_packet.get("related_nodes", [])
    _bullet(f"Focus service: {context_packet.get('focus_service')}")
    _bullet(f"Related nodes in blast radius: {len(related)}")
    for node in related:
        svc = node.get("service", "?")
        status = node.get("status", "?").upper()
        events = node.get("events", [])
        _sub(f"  {svc} [{status}] — {len(events)} events")
        # Show event summaries
        for ev in events[:5]:
            if isinstance(ev, dict):
                ev_type = ev.get("type", ev.get("kind", "event"))
                desc = ev.get("description", ev.get("summary", ""))
                if desc:
                    _sub(f"    [{ev_type}] {desc[:120]}")

    # =====================================================================
    # Step 4: LLM Analysis
    # =====================================================================
    _header("Running LLM root-cause analysis", "STEP 4/4")

    llm_client = get_client(
        provider=args.provider,
        model=args.model,
        api_key=args.api_key,
    )

    agent = RCAAgent(
        client=llm_client,
        github_output_path=args.github_events,
        code_index=code_index,
    )

    _bullet(f"Sending context to {args.provider}...")
    report = agent.analyze(context_packet)
    elapsed = _time.time() - t0

    # =====================================================================
    # Output
    # =====================================================================
    report_json = json.dumps(report, indent=2, default=str)

    if args.output:
        with open(args.output, "w") as f:
            f.write(report_json)

    _header("RCA REPORT")

    if isinstance(report, dict) and "root_cause_service" in report:
        print(f"""
  Root Cause Service:   {report.get('root_cause_service')}
  Fault Start Time:     {report.get('root_cause_datetime', 'N/A')}
  Confidence:           {report.get('confidence')}

  Reasoning:
  {'-'*60}
  {report.get('reasoning', 'N/A')}

  Recommended Action:
  {'-'*60}
  {report.get('recommended_action', 'N/A')}
""")
    else:
        print(report_json)

    print(f"  Pipeline completed in {elapsed:.1f}s")
    if args.output:
        print(f"  Full report saved to: {args.output}")

    # --- Slack ---
    if args.slack_channel or os.getenv("SLACK_BOT_TOKEN"):
        _header("Posting to Slack")
        _post_to_slack(report, context_packet, args)


# ---------------------------------------------------------------------------
# index — pre-build a code index
# ---------------------------------------------------------------------------

def cmd_index(args: argparse.Namespace) -> None:
    """Build a code index and save it to disk."""
    from rootscout.code_indexer import CodeIndexer

    print(BANNER)
    _header("Building code index")

    indexer = CodeIndexer(args.codebases)
    index = indexer.build_index()

    output = args.output or "rootscout_index.json"
    index.save(output)

    langs = {}
    for entry in index.files.values():
        langs[entry.language] = langs.get(entry.language, 0) + 1

    _bullet(f"Files indexed: {len(index.files)}")
    for lang, count in sorted(langs.items(), key=lambda x: -x[1]):
        _sub(f"{lang}: {count}")
    _bullet(f"Services detected: {len(index.service_map)}")
    _bullet(f"Index saved to: {output}")


# ---------------------------------------------------------------------------
# serve — start the FastAPI server
# ---------------------------------------------------------------------------

def cmd_serve(args: argparse.Namespace) -> None:
    """Start the RootScout FastAPI server."""
    os.environ.setdefault("HOST", args.host)
    os.environ.setdefault("PORT", str(args.port))
    if args.enable_graph:
        os.environ["ENABLE_GRAPH_BUILDER"] = "true"

    from rootscout.main import main as server_main
    server_main()


# ---------------------------------------------------------------------------
# Main parser
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="rootscout",
        description="RootScout — Autonomous SRE root-cause analysis",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # --- analyze ---
    p_analyze = subparsers.add_parser(
        "analyze",
        help="Run full RCA pipeline: ingest telemetry + analyze with LLM",
    )
    p_analyze.add_argument(
        "--telemetry", nargs="+", required=True,
        help="OTel export files or directories (.pb, .json)",
    )
    p_analyze.add_argument(
        "--incident-time", required=True,
        help="ISO 8601 timestamp of the incident (e.g., 2024-06-01T10:00:00Z)",
    )
    p_analyze.add_argument(
        "--failing-service", required=True,
        help="Name of the service that is alerting",
    )
    p_analyze.add_argument(
        "--codebases", nargs="+", default=None,
        help="Paths or GitHub URLs to index for code context",
    )
    p_analyze.add_argument(
        "--window-hours", type=float, default=10.0,
        help="Hours of telemetry to look back from incident time (default: 10)",
    )
    p_analyze.add_argument(
        "--provider", default="claude",
        help="LLM provider: claude, gemini, openai, mock (default: claude)",
    )
    p_analyze.add_argument(
        "--model", default=None,
        help="Specific model override (e.g., claude-opus-4-6, gpt-4o-mini)",
    )
    p_analyze.add_argument(
        "--api-key", default=None,
        help="API key for the LLM provider (or set via env var)",
    )
    p_analyze.add_argument(
        "--github-events", default=None,
        help="Path to GitHub events JSONL file for code change context",
    )
    p_analyze.add_argument(
        "--slack-channel", default=None,
        help="Slack channel to post report to (or set SLACK_ALERT_CHANNEL env var)",
    )
    p_analyze.add_argument(
        "--output", "-o", default=None,
        help="Output file path for the RCA report JSON",
    )
    p_analyze.set_defaults(func=cmd_analyze)

    # --- index ---
    p_index = subparsers.add_parser(
        "index",
        help="Pre-build a code index from codebases",
    )
    p_index.add_argument(
        "--codebases", nargs="+", required=True,
        help="Paths or GitHub URLs to index",
    )
    p_index.add_argument(
        "--output", "-o", default=None,
        help="Output path for the index JSON (default: rootscout_index.json)",
    )
    p_index.set_defaults(func=cmd_index)

    # --- serve ---
    p_serve = subparsers.add_parser(
        "serve",
        help="Start the RootScout FastAPI server (live OTel + webhook mode)",
    )
    p_serve.add_argument("--host", default="0.0.0.0", help="Host (default: 0.0.0.0)")
    p_serve.add_argument("--port", type=int, default=8000, help="Port (default: 8000)")
    p_serve.add_argument("--enable-graph", action="store_true", help="Enable graph builder")
    p_serve.set_defaults(func=cmd_serve)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
